# FIFA World Cup 2026 fixtures and results, adapted from
# https://github.com/openfootball/worldcup.json (2026/worldcup.json and
# 2026/worldcup.teams.json)
worldcup_data <- list(
  participant = list(
    list(id = 0, tournament_id = 0, name = "Mexico", image = "https://flagcdn.com/w80/mx.png"),
    list(id = 1, tournament_id = 0, name = "South Africa", image = "https://flagcdn.com/w80/za.png"),
    list(id = 2, tournament_id = 0, name = "South Korea", image = "https://flagcdn.com/w80/kr.png"),
    list(id = 3, tournament_id = 0, name = "Czech Republic", image = "https://flagcdn.com/w80/cz.png"),
    list(id = 4, tournament_id = 0, name = "Canada", image = "https://flagcdn.com/w80/ca.png"),
    list(id = 5, tournament_id = 0, name = "Bosnia & Herzegovina", image = "https://flagcdn.com/w80/ba.png"),
    list(id = 6, tournament_id = 0, name = "Qatar", image = "https://flagcdn.com/w80/qa.png"),
    list(id = 7, tournament_id = 0, name = "Switzerland", image = "https://flagcdn.com/w80/ch.png"),
    list(id = 8, tournament_id = 0, name = "Brazil", image = "https://flagcdn.com/w80/br.png"),
    list(id = 9, tournament_id = 0, name = "Morocco", image = "https://flagcdn.com/w80/ma.png"),
    list(id = 10, tournament_id = 0, name = "Haiti", image = "https://flagcdn.com/w80/ht.png"),
    list(id = 11, tournament_id = 0, name = "Scotland", image = "https://flagcdn.com/w80/gb-sct.png"),
    list(id = 12, tournament_id = 0, name = "USA", image = "https://flagcdn.com/w80/us.png"),
    list(id = 13, tournament_id = 0, name = "Paraguay", image = "https://flagcdn.com/w80/py.png"),
    list(id = 14, tournament_id = 0, name = "Australia", image = "https://flagcdn.com/w80/au.png"),
    list(id = 15, tournament_id = 0, name = "Turkey", image = "https://flagcdn.com/w80/tr.png"),
    list(id = 16, tournament_id = 0, name = "Germany", image = "https://flagcdn.com/w80/de.png"),
    list(id = 17, tournament_id = 0, name = "Curaçao", image = "https://flagcdn.com/w80/cw.png"),
    list(id = 18, tournament_id = 0, name = "Ivory Coast", image = "https://flagcdn.com/w80/ci.png"),
    list(id = 19, tournament_id = 0, name = "Ecuador", image = "https://flagcdn.com/w80/ec.png"),
    list(id = 20, tournament_id = 0, name = "Netherlands", image = "https://flagcdn.com/w80/nl.png"),
    list(id = 21, tournament_id = 0, name = "Japan", image = "https://flagcdn.com/w80/jp.png"),
    list(id = 22, tournament_id = 0, name = "Sweden", image = "https://flagcdn.com/w80/se.png"),
    list(id = 23, tournament_id = 0, name = "Tunisia", image = "https://flagcdn.com/w80/tn.png"),
    list(id = 24, tournament_id = 0, name = "Belgium", image = "https://flagcdn.com/w80/be.png"),
    list(id = 25, tournament_id = 0, name = "Egypt", image = "https://flagcdn.com/w80/eg.png"),
    list(id = 26, tournament_id = 0, name = "Iran", image = "https://flagcdn.com/w80/ir.png"),
    list(id = 27, tournament_id = 0, name = "New Zealand", image = "https://flagcdn.com/w80/nz.png"),
    list(id = 28, tournament_id = 0, name = "Spain", image = "https://flagcdn.com/w80/es.png"),
    list(id = 29, tournament_id = 0, name = "Cape Verde", image = "https://flagcdn.com/w80/cv.png"),
    list(id = 30, tournament_id = 0, name = "Saudi Arabia", image = "https://flagcdn.com/w80/sa.png"),
    list(id = 31, tournament_id = 0, name = "Uruguay", image = "https://flagcdn.com/w80/uy.png"),
    list(id = 32, tournament_id = 0, name = "France", image = "https://flagcdn.com/w80/fr.png"),
    list(id = 33, tournament_id = 0, name = "Senegal", image = "https://flagcdn.com/w80/sn.png"),
    list(id = 34, tournament_id = 0, name = "Iraq", image = "https://flagcdn.com/w80/iq.png"),
    list(id = 35, tournament_id = 0, name = "Norway", image = "https://flagcdn.com/w80/no.png"),
    list(id = 36, tournament_id = 0, name = "Argentina", image = "https://flagcdn.com/w80/ar.png"),
    list(id = 37, tournament_id = 0, name = "Algeria", image = "https://flagcdn.com/w80/dz.png"),
    list(id = 38, tournament_id = 0, name = "Austria", image = "https://flagcdn.com/w80/at.png"),
    list(id = 39, tournament_id = 0, name = "Jordan", image = "https://flagcdn.com/w80/jo.png"),
    list(id = 40, tournament_id = 0, name = "Portugal", image = "https://flagcdn.com/w80/pt.png"),
    list(id = 41, tournament_id = 0, name = "DR Congo", image = "https://flagcdn.com/w80/cd.png"),
    list(id = 42, tournament_id = 0, name = "Uzbekistan", image = "https://flagcdn.com/w80/uz.png"),
    list(id = 43, tournament_id = 0, name = "Colombia", image = "https://flagcdn.com/w80/co.png"),
    list(id = 44, tournament_id = 0, name = "England", image = "https://flagcdn.com/w80/gb-eng.png"),
    list(id = 45, tournament_id = 0, name = "Croatia", image = "https://flagcdn.com/w80/hr.png"),
    list(id = 46, tournament_id = 0, name = "Ghana", image = "https://flagcdn.com/w80/gh.png"),
    list(id = 47, tournament_id = 0, name = "Panama", image = "https://flagcdn.com/w80/pa.png")
  ),
  stage = list(
    list(
      id = 0,
      tournament_id = 0,
      name = "Group Stage",
      type = "round_robin",
      number = 1,
      settings = list(
        size = 48,
        groupCount = 12,
        roundRobinMode = "simple",
        grandFinal = "none",
        matchesChildCount = 0
      )
    ),
    list(
      id = 1,
      tournament_id = 0,
      name = "Knockout Stage",
      type = "single_elimination",
      number = 2,
      settings = list(
        size = 32,
        seedOrdering = list("natural"),
        grandFinal = "none",
        consolationFinal = TRUE,
        matchesChildCount = 0
      )
    )
  ),
  group = list(
    list(id = 0, stage_id = 0, number = 1),
    list(id = 1, stage_id = 0, number = 2),
    list(id = 2, stage_id = 0, number = 3),
    list(id = 3, stage_id = 0, number = 4),
    list(id = 4, stage_id = 0, number = 5),
    list(id = 5, stage_id = 0, number = 6),
    list(id = 6, stage_id = 0, number = 7),
    list(id = 7, stage_id = 0, number = 8),
    list(id = 8, stage_id = 0, number = 9),
    list(id = 9, stage_id = 0, number = 10),
    list(id = 10, stage_id = 0, number = 11),
    list(id = 11, stage_id = 0, number = 12)
  ),
  round = list(
    list(id = 0, number = 1, stage_id = 0, group_id = 0),
    list(id = 1, number = 2, stage_id = 0, group_id = 0),
    list(id = 2, number = 3, stage_id = 0, group_id = 0),
    list(id = 3, number = 1, stage_id = 0, group_id = 1),
    list(id = 4, number = 2, stage_id = 0, group_id = 1),
    list(id = 5, number = 3, stage_id = 0, group_id = 1),
    list(id = 6, number = 1, stage_id = 0, group_id = 2),
    list(id = 7, number = 2, stage_id = 0, group_id = 2),
    list(id = 8, number = 3, stage_id = 0, group_id = 2),
    list(id = 9, number = 1, stage_id = 0, group_id = 3),
    list(id = 10, number = 2, stage_id = 0, group_id = 3),
    list(id = 11, number = 3, stage_id = 0, group_id = 3),
    list(id = 12, number = 1, stage_id = 0, group_id = 4),
    list(id = 13, number = 2, stage_id = 0, group_id = 4),
    list(id = 14, number = 3, stage_id = 0, group_id = 4),
    list(id = 15, number = 1, stage_id = 0, group_id = 5),
    list(id = 16, number = 2, stage_id = 0, group_id = 5),
    list(id = 17, number = 3, stage_id = 0, group_id = 5),
    list(id = 18, number = 1, stage_id = 0, group_id = 6),
    list(id = 19, number = 2, stage_id = 0, group_id = 6),
    list(id = 20, number = 3, stage_id = 0, group_id = 6),
    list(id = 21, number = 1, stage_id = 0, group_id = 7),
    list(id = 22, number = 2, stage_id = 0, group_id = 7),
    list(id = 23, number = 3, stage_id = 0, group_id = 7),
    list(id = 24, number = 1, stage_id = 0, group_id = 8),
    list(id = 25, number = 2, stage_id = 0, group_id = 8),
    list(id = 26, number = 3, stage_id = 0, group_id = 8),
    list(id = 27, number = 1, stage_id = 0, group_id = 9),
    list(id = 28, number = 2, stage_id = 0, group_id = 9),
    list(id = 29, number = 3, stage_id = 0, group_id = 9),
    list(id = 30, number = 1, stage_id = 0, group_id = 10),
    list(id = 31, number = 2, stage_id = 0, group_id = 10),
    list(id = 32, number = 3, stage_id = 0, group_id = 10),
    list(id = 33, number = 1, stage_id = 0, group_id = 11),
    list(id = 34, number = 2, stage_id = 0, group_id = 11),
    list(id = 35, number = 3, stage_id = 0, group_id = 11),
    list(id = 36, number = 1, stage_id = 1, group_id = 0),
    list(id = 37, number = 2, stage_id = 1, group_id = 0),
    list(id = 38, number = 3, stage_id = 1, group_id = 0),
    list(id = 39, number = 4, stage_id = 1, group_id = 0),
    list(id = 40, number = 5, stage_id = 1, group_id = 0),
    list(id = 41, number = 1, stage_id = 1, group_id = -1)
  ),
  match = list(
    list(
      id = 0,
      number = 1,
      stage_id = 0,
      group_id = 0,
      round_id = 0,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 0, score = 2, result = "win"),
      opponent2 = list(id = 1, score = 0, result = "loss")
    ),
    list(
      id = 1,
      number = 2,
      stage_id = 0,
      group_id = 0,
      round_id = 0,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 2, score = 2, result = "win"),
      opponent2 = list(id = 3, score = 1, result = "loss")
    ),
    list(
      id = 2,
      number = 3,
      stage_id = 0,
      group_id = 0,
      round_id = 1,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 3, score = 1, result = "draw"),
      opponent2 = list(id = 1, score = 1, result = "draw")
    ),
    list(
      id = 3,
      number = 4,
      stage_id = 0,
      group_id = 0,
      round_id = 1,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 0, score = 1, result = "win"),
      opponent2 = list(id = 2, score = 0, result = "loss")
    ),
    list(
      id = 4,
      number = 5,
      stage_id = 0,
      group_id = 0,
      round_id = 2,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 3, score = 0, result = "loss"),
      opponent2 = list(id = 0, score = 3, result = "win")
    ),
    list(
      id = 5,
      number = 6,
      stage_id = 0,
      group_id = 0,
      round_id = 2,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 1, score = 1, result = "win"),
      opponent2 = list(id = 2, score = 0, result = "loss")
    ),
    list(
      id = 6,
      number = 7,
      stage_id = 0,
      group_id = 1,
      round_id = 3,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 4, score = 1, result = "draw"),
      opponent2 = list(id = 5, score = 1, result = "draw")
    ),
    list(
      id = 7,
      number = 8,
      stage_id = 0,
      group_id = 1,
      round_id = 3,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 6, score = 1, result = "draw"),
      opponent2 = list(id = 7, score = 1, result = "draw")
    ),
    list(
      id = 8,
      number = 9,
      stage_id = 0,
      group_id = 1,
      round_id = 4,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 7, score = 4, result = "win"),
      opponent2 = list(id = 5, score = 1, result = "loss")
    ),
    list(
      id = 9,
      number = 10,
      stage_id = 0,
      group_id = 1,
      round_id = 4,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 4, score = 6, result = "win"),
      opponent2 = list(id = 6, score = 0, result = "loss")
    ),
    list(
      id = 10,
      number = 11,
      stage_id = 0,
      group_id = 1,
      round_id = 5,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 7, score = 2, result = "win"),
      opponent2 = list(id = 4, score = 1, result = "loss")
    ),
    list(
      id = 11,
      number = 12,
      stage_id = 0,
      group_id = 1,
      round_id = 5,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 5, score = 3, result = "win"),
      opponent2 = list(id = 6, score = 1, result = "loss")
    ),
    list(
      id = 12,
      number = 13,
      stage_id = 0,
      group_id = 2,
      round_id = 6,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 8, score = 1, result = "draw"),
      opponent2 = list(id = 9, score = 1, result = "draw")
    ),
    list(
      id = 13,
      number = 14,
      stage_id = 0,
      group_id = 2,
      round_id = 6,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 10, score = 0, result = "loss"),
      opponent2 = list(id = 11, score = 1, result = "win")
    ),
    list(
      id = 14,
      number = 15,
      stage_id = 0,
      group_id = 2,
      round_id = 7,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 11, score = 0, result = "loss"),
      opponent2 = list(id = 9, score = 1, result = "win")
    ),
    list(
      id = 15,
      number = 16,
      stage_id = 0,
      group_id = 2,
      round_id = 7,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 8, score = 3, result = "win"),
      opponent2 = list(id = 10, score = 0, result = "loss")
    ),
    list(
      id = 16,
      number = 17,
      stage_id = 0,
      group_id = 2,
      round_id = 8,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 11, score = 0, result = "loss"),
      opponent2 = list(id = 8, score = 3, result = "win")
    ),
    list(
      id = 17,
      number = 18,
      stage_id = 0,
      group_id = 2,
      round_id = 8,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 9, score = 4, result = "win"),
      opponent2 = list(id = 10, score = 2, result = "loss")
    ),
    list(
      id = 18,
      number = 19,
      stage_id = 0,
      group_id = 3,
      round_id = 9,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 12, score = 4, result = "win"),
      opponent2 = list(id = 13, score = 1, result = "loss")
    ),
    list(
      id = 19,
      number = 20,
      stage_id = 0,
      group_id = 3,
      round_id = 9,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 14, score = 2, result = "win"),
      opponent2 = list(id = 15, score = 0, result = "loss")
    ),
    list(
      id = 20,
      number = 21,
      stage_id = 0,
      group_id = 3,
      round_id = 10,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 12, score = 2, result = "win"),
      opponent2 = list(id = 14, score = 0, result = "loss")
    ),
    list(
      id = 21,
      number = 22,
      stage_id = 0,
      group_id = 3,
      round_id = 10,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 15, score = 0, result = "loss"),
      opponent2 = list(id = 13, score = 1, result = "win")
    ),
    list(
      id = 22,
      number = 23,
      stage_id = 0,
      group_id = 3,
      round_id = 11,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 15, score = 3, result = "win"),
      opponent2 = list(id = 12, score = 2, result = "loss")
    ),
    list(
      id = 23,
      number = 24,
      stage_id = 0,
      group_id = 3,
      round_id = 11,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 13, score = 0, result = "draw"),
      opponent2 = list(id = 14, score = 0, result = "draw")
    ),
    list(
      id = 24,
      number = 25,
      stage_id = 0,
      group_id = 4,
      round_id = 12,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 16, score = 7, result = "win"),
      opponent2 = list(id = 17, score = 1, result = "loss")
    ),
    list(
      id = 25,
      number = 26,
      stage_id = 0,
      group_id = 4,
      round_id = 12,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 18, score = 1, result = "win"),
      opponent2 = list(id = 19, score = 0, result = "loss")
    ),
    list(
      id = 26,
      number = 27,
      stage_id = 0,
      group_id = 4,
      round_id = 13,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 16, score = 2, result = "win"),
      opponent2 = list(id = 18, score = 1, result = "loss")
    ),
    list(
      id = 27,
      number = 28,
      stage_id = 0,
      group_id = 4,
      round_id = 13,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 19, score = 0, result = "draw"),
      opponent2 = list(id = 17, score = 0, result = "draw")
    ),
    list(
      id = 28,
      number = 29,
      stage_id = 0,
      group_id = 4,
      round_id = 14,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 17, score = 0, result = "loss"),
      opponent2 = list(id = 18, score = 2, result = "win")
    ),
    list(
      id = 29,
      number = 30,
      stage_id = 0,
      group_id = 4,
      round_id = 14,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 19, score = 2, result = "win"),
      opponent2 = list(id = 16, score = 1, result = "loss")
    ),
    list(
      id = 30,
      number = 31,
      stage_id = 0,
      group_id = 5,
      round_id = 15,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 20, score = 2, result = "draw"),
      opponent2 = list(id = 21, score = 2, result = "draw")
    ),
    list(
      id = 31,
      number = 32,
      stage_id = 0,
      group_id = 5,
      round_id = 15,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 22, score = 5, result = "win"),
      opponent2 = list(id = 23, score = 1, result = "loss")
    ),
    list(
      id = 32,
      number = 33,
      stage_id = 0,
      group_id = 5,
      round_id = 16,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 20, score = 5, result = "win"),
      opponent2 = list(id = 22, score = 1, result = "loss")
    ),
    list(
      id = 33,
      number = 34,
      stage_id = 0,
      group_id = 5,
      round_id = 16,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 23, score = 0, result = "loss"),
      opponent2 = list(id = 21, score = 4, result = "win")
    ),
    list(
      id = 34,
      number = 35,
      stage_id = 0,
      group_id = 5,
      round_id = 17,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 21, score = 1, result = "draw"),
      opponent2 = list(id = 22, score = 1, result = "draw")
    ),
    list(
      id = 35,
      number = 36,
      stage_id = 0,
      group_id = 5,
      round_id = 17,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 23, score = 1, result = "loss"),
      opponent2 = list(id = 20, score = 3, result = "win")
    ),
    list(
      id = 36,
      number = 37,
      stage_id = 0,
      group_id = 6,
      round_id = 18,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 24, score = 1, result = "draw"),
      opponent2 = list(id = 25, score = 1, result = "draw")
    ),
    list(
      id = 37,
      number = 38,
      stage_id = 0,
      group_id = 6,
      round_id = 18,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 26, score = 2, result = "draw"),
      opponent2 = list(id = 27, score = 2, result = "draw")
    ),
    list(
      id = 38,
      number = 39,
      stage_id = 0,
      group_id = 6,
      round_id = 19,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 24, score = 0, result = "draw"),
      opponent2 = list(id = 26, score = 0, result = "draw")
    ),
    list(
      id = 39,
      number = 40,
      stage_id = 0,
      group_id = 6,
      round_id = 19,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 27, score = 1, result = "loss"),
      opponent2 = list(id = 25, score = 3, result = "win")
    ),
    list(
      id = 40,
      number = 41,
      stage_id = 0,
      group_id = 6,
      round_id = 20,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 25, score = 1, result = "draw"),
      opponent2 = list(id = 26, score = 1, result = "draw")
    ),
    list(
      id = 41,
      number = 42,
      stage_id = 0,
      group_id = 6,
      round_id = 20,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 27, score = 1, result = "loss"),
      opponent2 = list(id = 24, score = 5, result = "win")
    ),
    list(
      id = 42,
      number = 43,
      stage_id = 0,
      group_id = 7,
      round_id = 21,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 28, score = 0, result = "draw"),
      opponent2 = list(id = 29, score = 0, result = "draw")
    ),
    list(
      id = 43,
      number = 44,
      stage_id = 0,
      group_id = 7,
      round_id = 21,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 30, score = 1, result = "draw"),
      opponent2 = list(id = 31, score = 1, result = "draw")
    ),
    list(
      id = 44,
      number = 45,
      stage_id = 0,
      group_id = 7,
      round_id = 22,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 28, score = 4, result = "win"),
      opponent2 = list(id = 30, score = 0, result = "loss")
    ),
    list(
      id = 45,
      number = 46,
      stage_id = 0,
      group_id = 7,
      round_id = 22,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 31, score = 2, result = "draw"),
      opponent2 = list(id = 29, score = 2, result = "draw")
    ),
    list(
      id = 46,
      number = 47,
      stage_id = 0,
      group_id = 7,
      round_id = 23,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 29, score = 0, result = "draw"),
      opponent2 = list(id = 30, score = 0, result = "draw")
    ),
    list(
      id = 47,
      number = 48,
      stage_id = 0,
      group_id = 7,
      round_id = 23,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 31, score = 0, result = "loss"),
      opponent2 = list(id = 28, score = 1, result = "win")
    ),
    list(
      id = 48,
      number = 49,
      stage_id = 0,
      group_id = 8,
      round_id = 24,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 32, score = 3, result = "win"),
      opponent2 = list(id = 33, score = 1, result = "loss")
    ),
    list(
      id = 49,
      number = 50,
      stage_id = 0,
      group_id = 8,
      round_id = 24,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 34, score = 1, result = "loss"),
      opponent2 = list(id = 35, score = 4, result = "win")
    ),
    list(
      id = 50,
      number = 51,
      stage_id = 0,
      group_id = 8,
      round_id = 25,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 32, score = 3, result = "win"),
      opponent2 = list(id = 34, score = 0, result = "loss")
    ),
    list(
      id = 51,
      number = 52,
      stage_id = 0,
      group_id = 8,
      round_id = 25,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 35, score = 3, result = "win"),
      opponent2 = list(id = 33, score = 2, result = "loss")
    ),
    list(
      id = 52,
      number = 53,
      stage_id = 0,
      group_id = 8,
      round_id = 26,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 35, score = 1, result = "loss"),
      opponent2 = list(id = 32, score = 4, result = "win")
    ),
    list(
      id = 53,
      number = 54,
      stage_id = 0,
      group_id = 8,
      round_id = 26,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 33, score = 5, result = "win"),
      opponent2 = list(id = 34, score = 0, result = "loss")
    ),
    list(
      id = 54,
      number = 55,
      stage_id = 0,
      group_id = 9,
      round_id = 27,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 36, score = 3, result = "win"),
      opponent2 = list(id = 37, score = 0, result = "loss")
    ),
    list(
      id = 55,
      number = 56,
      stage_id = 0,
      group_id = 9,
      round_id = 27,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 38, score = 3, result = "win"),
      opponent2 = list(id = 39, score = 1, result = "loss")
    ),
    list(
      id = 56,
      number = 57,
      stage_id = 0,
      group_id = 9,
      round_id = 28,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 36, score = 2, result = "win"),
      opponent2 = list(id = 38, score = 0, result = "loss")
    ),
    list(
      id = 57,
      number = 58,
      stage_id = 0,
      group_id = 9,
      round_id = 28,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 39, score = 1, result = "loss"),
      opponent2 = list(id = 37, score = 2, result = "win")
    ),
    list(
      id = 58,
      number = 59,
      stage_id = 0,
      group_id = 9,
      round_id = 29,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 37, score = 3, result = "draw"),
      opponent2 = list(id = 38, score = 3, result = "draw")
    ),
    list(
      id = 59,
      number = 60,
      stage_id = 0,
      group_id = 9,
      round_id = 29,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 39, score = 1, result = "loss"),
      opponent2 = list(id = 36, score = 3, result = "win")
    ),
    list(
      id = 60,
      number = 61,
      stage_id = 0,
      group_id = 10,
      round_id = 30,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 40, score = 1, result = "draw"),
      opponent2 = list(id = 41, score = 1, result = "draw")
    ),
    list(
      id = 61,
      number = 62,
      stage_id = 0,
      group_id = 10,
      round_id = 30,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 42, score = 1, result = "loss"),
      opponent2 = list(id = 43, score = 3, result = "win")
    ),
    list(
      id = 62,
      number = 63,
      stage_id = 0,
      group_id = 10,
      round_id = 31,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 40, score = 5, result = "win"),
      opponent2 = list(id = 42, score = 0, result = "loss")
    ),
    list(
      id = 63,
      number = 64,
      stage_id = 0,
      group_id = 10,
      round_id = 31,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 43, score = 1, result = "win"),
      opponent2 = list(id = 41, score = 0, result = "loss")
    ),
    list(
      id = 64,
      number = 65,
      stage_id = 0,
      group_id = 10,
      round_id = 32,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 43, score = 0, result = "draw"),
      opponent2 = list(id = 40, score = 0, result = "draw")
    ),
    list(
      id = 65,
      number = 66,
      stage_id = 0,
      group_id = 10,
      round_id = 32,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 41, score = 3, result = "win"),
      opponent2 = list(id = 42, score = 1, result = "loss")
    ),
    list(
      id = 66,
      number = 67,
      stage_id = 0,
      group_id = 11,
      round_id = 33,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 44, score = 4, result = "win"),
      opponent2 = list(id = 45, score = 2, result = "loss")
    ),
    list(
      id = 67,
      number = 68,
      stage_id = 0,
      group_id = 11,
      round_id = 33,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 46, score = 1, result = "win"),
      opponent2 = list(id = 47, score = 0, result = "loss")
    ),
    list(
      id = 68,
      number = 69,
      stage_id = 0,
      group_id = 11,
      round_id = 34,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 44, score = 0, result = "draw"),
      opponent2 = list(id = 46, score = 0, result = "draw")
    ),
    list(
      id = 69,
      number = 70,
      stage_id = 0,
      group_id = 11,
      round_id = 34,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 47, score = 0, result = "loss"),
      opponent2 = list(id = 45, score = 1, result = "win")
    ),
    list(
      id = 70,
      number = 71,
      stage_id = 0,
      group_id = 11,
      round_id = 35,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 47, score = 0, result = "loss"),
      opponent2 = list(id = 44, score = 2, result = "win")
    ),
    list(
      id = 71,
      number = 72,
      stage_id = 0,
      group_id = 11,
      round_id = 35,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 45, score = 2, result = "win"),
      opponent2 = list(id = 46, score = 1, result = "loss")
    ),
    list(
      id = 72,
      number = 73,
      stage_id = 1,
      group_id = 0,
      round_id = 36,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 16, score = 1, result = "loss"),
      opponent2 = list(id = 13, score = 1, result = "win")
    ),
    list(
      id = 73,
      number = 74,
      stage_id = 1,
      group_id = 0,
      round_id = 36,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 32, score = 3, result = "win"),
      opponent2 = list(id = 22, score = 0, result = "loss")
    ),
    list(
      id = 74,
      number = 75,
      stage_id = 1,
      group_id = 0,
      round_id = 36,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 1, score = 0, result = "loss"),
      opponent2 = list(id = 4, score = 1, result = "win")
    ),
    list(
      id = 75,
      number = 76,
      stage_id = 1,
      group_id = 0,
      round_id = 36,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 20, score = 1, result = "loss"),
      opponent2 = list(id = 9, score = 1, result = "win")
    ),
    list(
      id = 76,
      number = 77,
      stage_id = 1,
      group_id = 0,
      round_id = 36,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 40, score = 2, result = "win"),
      opponent2 = list(id = 45, score = 1, result = "loss")
    ),
    list(
      id = 77,
      number = 78,
      stage_id = 1,
      group_id = 0,
      round_id = 36,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 28, score = 3, result = "win"),
      opponent2 = list(id = 38, score = 0, result = "loss")
    ),
    list(
      id = 78,
      number = 79,
      stage_id = 1,
      group_id = 0,
      round_id = 36,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 12, score = 2, result = "win"),
      opponent2 = list(id = 5, score = 0, result = "loss")
    ),
    list(
      id = 79,
      number = 80,
      stage_id = 1,
      group_id = 0,
      round_id = 36,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 24, score = 3, result = "win"),
      opponent2 = list(id = 33, score = 2, result = "loss")
    ),
    list(
      id = 80,
      number = 81,
      stage_id = 1,
      group_id = 0,
      round_id = 36,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 8, score = 2, result = "win"),
      opponent2 = list(id = 21, score = 1, result = "loss")
    ),
    list(
      id = 81,
      number = 82,
      stage_id = 1,
      group_id = 0,
      round_id = 36,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 18, score = 1, result = "loss"),
      opponent2 = list(id = 35, score = 2, result = "win")
    ),
    list(
      id = 82,
      number = 83,
      stage_id = 1,
      group_id = 0,
      round_id = 36,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 0, score = 2, result = "win"),
      opponent2 = list(id = 19, score = 0, result = "loss")
    ),
    list(
      id = 83,
      number = 84,
      stage_id = 1,
      group_id = 0,
      round_id = 36,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 44, score = 2, result = "win"),
      opponent2 = list(id = 41, score = 1, result = "loss")
    ),
    list(
      id = 84,
      number = 85,
      stage_id = 1,
      group_id = 0,
      round_id = 36,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 36, score = 3, result = "win"),
      opponent2 = list(id = 29, score = 2, result = "loss")
    ),
    list(
      id = 85,
      number = 86,
      stage_id = 1,
      group_id = 0,
      round_id = 36,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 14, score = 1, result = "loss"),
      opponent2 = list(id = 25, score = 1, result = "win")
    ),
    list(
      id = 86,
      number = 87,
      stage_id = 1,
      group_id = 0,
      round_id = 36,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 7, score = 2, result = "win"),
      opponent2 = list(id = 37, score = 0, result = "loss")
    ),
    list(
      id = 87,
      number = 88,
      stage_id = 1,
      group_id = 0,
      round_id = 36,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 43, score = 1, result = "win"),
      opponent2 = list(id = 46, score = 0, result = "loss")
    ),
    list(
      id = 88,
      number = 89,
      stage_id = 1,
      group_id = 0,
      round_id = 37,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 13, score = 0, result = "loss"),
      opponent2 = list(id = 32, score = 1, result = "win")
    ),
    list(
      id = 89,
      number = 90,
      stage_id = 1,
      group_id = 0,
      round_id = 37,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 4, score = 0, result = "loss"),
      opponent2 = list(id = 9, score = 3, result = "win")
    ),
    list(
      id = 90,
      number = 91,
      stage_id = 1,
      group_id = 0,
      round_id = 37,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 40, score = 0, result = "loss"),
      opponent2 = list(id = 28, score = 1, result = "win")
    ),
    list(
      id = 91,
      number = 92,
      stage_id = 1,
      group_id = 0,
      round_id = 37,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 12, score = 1, result = "loss"),
      opponent2 = list(id = 24, score = 4, result = "win")
    ),
    list(
      id = 92,
      number = 93,
      stage_id = 1,
      group_id = 0,
      round_id = 37,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 8, score = 1, result = "loss"),
      opponent2 = list(id = 35, score = 2, result = "win")
    ),
    list(
      id = 93,
      number = 94,
      stage_id = 1,
      group_id = 0,
      round_id = 37,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 0, score = 2, result = "loss"),
      opponent2 = list(id = 44, score = 3, result = "win")
    ),
    list(
      id = 94,
      number = 95,
      stage_id = 1,
      group_id = 0,
      round_id = 37,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 36, score = 3, result = "win"),
      opponent2 = list(id = 25, score = 2, result = "loss")
    ),
    list(
      id = 95,
      number = 96,
      stage_id = 1,
      group_id = 0,
      round_id = 37,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 7, score = 0, result = "win"),
      opponent2 = list(id = 43, score = 0, result = "loss")
    ),
    list(
      id = 96,
      number = 97,
      stage_id = 1,
      group_id = 0,
      round_id = 38,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 32, score = 2, result = "win"),
      opponent2 = list(id = 9, score = 0, result = "loss")
    ),
    list(
      id = 97,
      number = 98,
      stage_id = 1,
      group_id = 0,
      round_id = 38,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 28, score = 2, result = "win"),
      opponent2 = list(id = 24, score = 1, result = "loss")
    ),
    list(
      id = 98,
      number = 99,
      stage_id = 1,
      group_id = 0,
      round_id = 38,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 35, score = 1, result = "loss"),
      opponent2 = list(id = 44, score = 2, result = "win")
    ),
    list(
      id = 99,
      number = 100,
      stage_id = 1,
      group_id = 0,
      round_id = 38,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 36, score = 3, result = "win"),
      opponent2 = list(id = 7, score = 1, result = "loss")
    ),
    list(
      id = 100,
      number = 101,
      stage_id = 1,
      group_id = 0,
      round_id = 39,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 32, score = 0, result = "loss"),
      opponent2 = list(id = 28, score = 2, result = "win")
    ),
    list(
      id = 101,
      number = 102,
      stage_id = 1,
      group_id = 0,
      round_id = 39,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 44, score = 1, result = "loss"),
      opponent2 = list(id = 36, score = 2, result = "win")
    ),
    list(
      id = 102,
      number = 103,
      stage_id = 1,
      group_id = 0,
      round_id = 40,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 28, score = 1, result = "win"),
      opponent2 = list(id = 36, score = 0, result = "loss")
    ),
    list(
      id = 103,
      number = 104,
      stage_id = 1,
      group_id = -1,
      round_id = 41,
      child_count = 0,
      status = 4,
      opponent1 = list(id = 32, score = 4, result = "loss"),
      opponent2 = list(id = 44, score = 6, result = "win")
    )
  ),
  match_game = list()
)

# Split by stage so the app can let people flip between the two phases
# without cramming both into a single, very tall bracket.
worldcup_groups <- list(
  participant = worldcup_data$participant,
  stage = Filter(function(s) s$id == 0, worldcup_data$stage),
  group = worldcup_data$group,
  round = Filter(function(r) r$stage_id == 0, worldcup_data$round),
  match = Filter(function(m) m$stage_id == 0, worldcup_data$match),
  match_game = list()
)

worldcup_knockout <- list(
  participant = worldcup_data$participant,
  stage = Filter(function(s) s$id == 1, worldcup_data$stage),
  round = Filter(function(r) r$stage_id == 1, worldcup_data$round),
  match = Filter(function(m) m$stage_id == 1, worldcup_data$match),
  match_game = list()
)

# Stadium-at-night palette for bracketsViewer()'s theme argument: deep pitch
# green backgrounds, gold for winners, emerald for the connector lines.
worldcup_theme <- list(
  primaryBackground = "#0e2a1f",
  secondaryBackground = "#123322",
  matchBackground = "#143826",
  fontColor = "#f4efe1",
  winColor = "#f2c14e",
  lossColor = "#c96a6a",
  labelColor = "#cdd8cd",
  hintColor = "#7fa08d",
  connectorColor = "#1fd694",
  borderColor = "rgba(255, 255, 255, 0.08)",
  borderHoverColor = "#f2c14e",
  borderSelectedColor = "#ffe17d",
  matchBorderRadius = "10px",
  participantImageSize = "30px"
)

worldcup_css <- "bracket-styling.scss"
